# Generated by Django 3.0.1 on 2020-06-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
