# Generated by Django 3.0.1 on 2020-07-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200628_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Channel Invite: NULL', max_length=4096),
            preserve_default=False,
        ),
    ]
