# Generated by Django 3.0.1 on 2020-06-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('channel', '0002_channelmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
            ],
        ),
    ]
