# Generated by Django 3.0.1 on 2020-06-28 01:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0004_auto_20200628_0122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelinvite',
            unique_together={('user', 'channel')},
        ),
    ]
